# Numpy

Numpy is a python library that is widely used for mathematics, computer vision and a wide variety of other applications.

The main data structure in Numpy is the `array`. Most of this tutorial will focus on how to create and manipulate arrays.

First of all we need to import the numpy library. Here I've used the `as` syntax to create an alias for `numpy`. This means we can refer to it using the shorthand `np` in the code.

In [17]:
import numpy as np

A numpy array stores a number of elements of the same datatype. In this way it is similar to a python list, but they address some of the shortcomings of python lists. 

Whilst lists are one-dimensional, numpy arrays can have any number of dimensions, so they can represent vectors, matrices or tensors.

Unlike lists, numpy arrays have a set datatype and will only contain elements of that type. This is more restrictive, but means that arrays are more memory-efficient and performing operations on them is faster.

Arrays can be created in a number of ways:

In [18]:
# Creating from python lists:
vector = np.array([0,1,2,3])
matrix = np.array([ [1, 0, 0, 0],
                    [0, 1, 0, 0],
                    [0, 0, 1, 0],
                    [0, 0, 0, 1]])

# Making arrays of ones or zeros
ones = np.ones([10,10])
zeros = np.ones([3,5,2])

# Making a 4x4 identity matrix
identity = np.eye(4)

# Making random arrays
rand_array = np.random.random([5,2]) # Drawn from uniform random distribution on [0,1)
rand_array2 = np.random.normal([3,3,3]) #Drawn from a standard normal distribution (mean 0, stdev 1)

They are indexed in the same way as arrays, using square brackets. When the array has more than one dimension, the indices are separated by commas.

In [19]:
a = vector[2]
print(a)
b = matrix[3,3]
print(b)

2
1


Slices also work on numpy arrays, just like lists.

In [20]:
print(vector[1:])
print(matrix[:,2])

[1 2 3]
[0 0 1 0]


You can find out the dimensions of an array using the `shape` property.

In [21]:
print(rand_array.shape)
print(rand_array.shape[1]) # shape is a tuple, so you can access elements of it

(5, 2)
2


Arrays have a set datatype, and all elements of an array must be of the same type. However, we can convert arrays from one type to another.

In [22]:
print(vector.dtype) # vector was initially made from a list of ints, so its type is int32
float_vector = vector.astype(np.float32) # but we can convert it to an array of floats
print(float_vector.dtype)

int32
float32


The types available in numpy start with the format, like `int`, `uint` (unsigned int), `float` or `complex`. They end in an integer that says how many bits each item in the array takes up.

For example, `np.float32` is a 32-bit (single-precision) floating point datatype. `np.uint8` is an 8-bit unsigned integer datatype.

Mathematical operations work on arrays, and all of the standard operations `+ - * /` work element-wise.

This means they're equivalent to running through the arrays in a for loop and applying the operation to each pair of elements, like this:

In [23]:
array_1 = np.array([1,1,1])
array_2 = np.array([2,2,2])

# You could multiply these arrays element-wise with a for loop like this:
result = np.zeros([3])
for i in range(array_1.shape[0]):
    result[i] = array_1[i] * array_2[i]
print(result)

# But using the operator * is quicker to write, and runs faster too:
result = array_1 * array_2

[2. 2. 2.]


Note that `array_1 * array_2` *does not* perform matrix multiplication. For this you must use `np.matmul()`.

In [24]:
array_1 = np.eye(3)
array_2 = np.ones([3,3])*2.0

# This will do element-wise multiplication, and give a diagonal matrix.
print("Multiply\n", array_1 * array_2)

# This does proper matrix multiplication with an identity matrix, so will just output array_2.
print("Matrix multiply\n", np.matmul(array_1, array_2))

Multiply
 [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Matrix multiply
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
